services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: co2-backend
    ports:
      - "8000:8000"
    volumes:
      - ./scripts:/app/scripts
      - ./database:/app/database
      - ./models:/app/models
      - ./logs:/app/logs
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: co2-frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./scripts:/app/scripts
      - ./database:/app/database
      - ./models:/app/models
      - ./logs:/app/logs
    restart: always

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    container_name: co2-scheduler
    depends_on:
      - backend
    volumes:
      - ./scripts:/app/scripts
      - ./database:/app/database
      - ./models:/app/models
      - ./logs:/app/logs
    restart: always
