# Dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy all files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose Streamlit and FastAPI ports
EXPOSE 8501
EXPOSE 8000

# Command for Docker Compose (default is FastAPI server)
CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "8000"]
